version: '2'

services:

  snaxter-portfolio-demo:
    container_name: snaxter-portfolio-demo
    build:
      context: https://github.com/ScyDev/snaxter-demo-snapshot-all-in-one.git
      # dockerfile: reaction.dev.src.docker
    # volumes:
    #   - "./:/var/www/src/"
    ports:
      - 80:3000
