version: '2'

services:

  snaxter-portfolio-demo:
    container_name: snaxter-portfolio-demo
    build:
      context: ./
      dockerfile: ./docker/reaction.dev.src.docker
      # args:
      #   buildno: 1
    volumes:
      - "/media/thluks/PHOBOS_II/PROJECTS/04 OLD/Snaxter/meteor/reaction:/var/www/src/"
    ports:
      - 80:3000
